// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxxavylpbzwfqpqmspis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4eGF2eWxwYnp3ZnFwcW1zcGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDg1MzYsImV4cCI6MjA2NzM4NDUzNn0.k6CBPafOxOJHHoyui2tN7QhI9Yw1TgTDu69ht2h5SUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});